name: CI/CD for Notebook backend service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    secrets:
      GCLOUD_SA_KEY:
        required: true

env:
  IMAGE_URL: us-central1-docker.pkg.dev/notebook-service-442013/notebook-backend:latest

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Install dependencies
      run: go mod tidy

    - name: Build application
      run: go build -o app main.go

    - name: Build Docker image
      uses: docker/setup-buildx-action@v2
    - run: |
        docker build -t $IMAGE_URL .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Run tests
      run: go test ./...

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: develop
    env:
      GCE_INSTANCE: "nb-service-staging"
      GCE_ZONE: "us-central1-c"
    steps:
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SA_KEY }}
    - run: gcloud auth configure-docker --quiet

    - name: Push Docker image to GCR
      run: |
        docker push $IMAGE_URL

    - name: Deploy to GCE with Docker
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ vars.GCE_IP }}
        username: ${{ vars.GCE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull $IMAGE_URL
          docker stop nb-backend || true
          docker rm nb-backend || true
          docker run -d --name nb-backend -p 80:8080 $IMAGE_URL